setClass("NetworkStructList", representation(models = "list"), contains = "NetworkStruct")


#' Constructor for class NetworkStructList -- a list of network model structure information. 
#' 
#' These are the random edge partitions used in the network hypothesis testing. 
#' 
#' @param Nnodes Number of nodes for each network
#' @param Nmodels Number of random edge partitions to generate
#' @param type Type of random edge partition to generate
#' @param model_param List of model parameters; see set_model_param(). 
#' 
#' @return Object of class NetworkStructList
#' 
#' @export
#' 
NetworkStructList = function(Nnodes = 10, Nmodels = 10, type = "none", model_param = set_model_param()) {
  # TODO: [Improvement] 'type' can be a vector, and call it vectorized => resulting network list has multiple types
  res = replicate(n = Nmodels, expr = NetworkStruct(Nnodes = Nnodes, type = type, model_param = model_param))
  netsl = new("NetworkStructList", Nnodes = Nnodes, models = res)
  return(netsl)
}


#' Extract the type of network model
#' 
#' @param NetM Object of class NetworkStructList
#' 
#' @return character vector of types
#' 
#' @export
#' 
getNetType.NetworkStructList = function(NetM) {
  return(sapply(NetM@models, getNetType))
}
setMethod("getNetType", signature(NetM = "NetworkStructList"), getNetType.NetworkStructList)


#' Computes the p-values for each random partition in a NetworkStructList
#' 
#' @param NetS NetworkStructList to use
#' @param adja1 Adjacency matrix/array
#' @param adja2 Adjacency matrix/array
#' @param Nobs Number of observations per input
#' @param pl parameter list, generated by set_sim_param()
#' 
#' @return List of arrays containing p-values
#' 
#' @export
#' 
computePval.NetworkStructList = function(NetS, adja1, adja2, Nobs, pl) {
  res = lapply(NetS@models, function(x) { computePval(x, adja1, adja2, Nobs, pl) } )
  return(res)
}
setMethod("computePval", signature(NetS = "NetworkStructList"), computePval.NetworkStructList)


