
## TODO: Check if this function is old... why does pval_adj_fx work that way? 
#' Do simulations for the hypothesis testing, using the new code. 
#' 
#' @param gen_NetMPair [\code{\link{NetworkModelPair}}] :: Generating pair of models
#' @param fit_NetSList [\code{\link{NetworkStructList}}] :: List of fixed fitting structures (can be NULL -> randomly generate given parameters)
#' @param fitm_params [list] :: Output of \code{\link{set_model_params}}, specify the type of fitting model
#' @param adjm_list [] :: Can input a list of adjacency matrices. If done, then the generating model pair is ignored. 
#' @param Nobs [int, 1] :: Number network observations (default = 1)
#' @param Nsim [int, 100] :: Number of simulations to do
#' @param pl [List, \link{set_sim_param}()] :: Parameter list for testing procedure
#' @param verbose [int, 0] :: level: 0 -- no output. > 3 -- full output
#' 
#' @return List of results
#' 
#' @export
#' 
sim_hyptest = function(gen_NetMPair, fit_NetSList = NULL, fitm_params = set_model_param(), adjm_list = NULL, 
                       Nobs = 1, Nsim = 100, pl = set_sim_param(), verbose = 0) {
  ## Test case
  if(FALSE) {
    library(netcompLib); library(abind)
    load("../../network-comparison/netcomp-project/data/method_data/small_samp_DFcorr.Rdata")
    
    gen_NetMPair = NetworkModelPair(set_model_param(), set_model_param(), is_null = FALSE)
    fit_NetSList = NetworkStructList(Nmodels = 100)
    Nobs = 1; Nsim = 100; verbose = TRUE;
    pl = set_sim_param(cc_adj = c(0,1,2), thres_ignore = c(5, 10), n_models = c(1, 25, 50, 100))
  }
  
  # Check that enough models were generated
  Nfit = max(pl$n_models)
  if (is.null(fit_NetSList)) { 
    fit_NetSList = NetworkStructList(Nmodels = Nfit, model_params = fitm_params) 
  }

  if (Nfit > length(fit_NetSList@models)) { stop("Not enough fitted models generated") }
  partial_indices = lapply(pl$n_models, function(x) { 1:x })
  
  ## Setup storage
  result_list = list(); for(f in seq_along(pl$pval_adj$fx)) { result_list[[f]] = list() } 
  pval_reslist = list()  
  
  ## Generate two lists of adjacency arrays
  if (is.null(adjm_list)) { adjm_list = sampleNetwork(gen_NetMPair, Nsim = Nsim) }
  
  ## Do simulations
  for(j in 1:Nsim) {  
    if (verbose > 3) { cat("."); if (j %% floor(Nsim/10) == 0) { print(paste("Simulation number:", j)) } }
    pval_results = computePval(fit_NetSList, adja1 = adjm_list[[1]][[j]], adja2 = adjm_list[[2]][[j]], pl = pl, Nobs = 1)
    pval_reslist[[j]] = abind(pval_results, along = 3)
    
    for(f in seq_along(pl$pval_adj$fx)) {
      result_list[[f]][[j]] = setup_array(pl)
      for (k in seq_along(pl$n_models)) {
        for (a in seq_along(pl$alphas)) {
          result_list[[f]][[j]][,,a,k] = apply(pval_reslist[[j]][,,partial_indices[[k]], drop = FALSE], c(1,2),pl$pval_adj$fx[[f]])
        }
      }
    }
  }
  return(result_list)
}


## TODO: [Documentation-AUTO] Check/fix Roxygen2 Documentation (sim_critvals)
#' Simulates critical values for each type of multiple testing adjustment
#' 
#' @param NetMPair [] :: Pair of network models: These serve as the 'null hypothesis' models from which to generate critical values from
#' @param Nsim [int, 500] :: Number of simulations
#' @param Nobs [int, 1] :: Number of network observations
#' @param fit_NetSList [] :: temp
#' @param fit_models_params [] :: parameter settings
#' @param pl [List] :: List of simulation parameters, typically generated by a call to set_sim_param()
#' @param verbose [int, 0] :: Verbosity level, output stuff if > 2. 
#' 
#' @return [List] :: list of arrays of critical values
#' 
#' @export
#' 
sim_critvals = function(NetMPair, Nsim = 500, Nobs = 1, fit_NetSList = NULL, fit_models_params = set_model_param(), pl = set_sim_param(),verbose = 0) { 
  
  if (is.null(fit_NetSList)) {
    fit_NetSList = NetworkStructList(model_params = fit_models_params, Nmodels = max(pl$n_models))
  }
  
  if (verbose > 2) { print("** Calling sim_hyptest **")}
  sim_vals = sim_hyptest(
    gen_NetMPair = NetMPair, fit_NetSList = fit_NetSList, 
    Nobs = Nobs, Nsim = Nsim, pl = pl, verbose = verbose)
  
  if (verbose > 2) { print("** Aggregating results **")}
  res_list = list()
  cases = expand.grid(pl)
  for(j in seq_along(pl$pval_adj$fx)) {
    res_list[[j]] = setup_array(pl)
    for(k in seq_len(nrow(cases))) {
      res_list[[j]][cases$cc_adj[k] == pl$cc_adj, 
                    cases$thres_ignore[k] == pl$thres_ignore,
                    cases$alphas[k] == pl$alphas, 
                    cases$n_models[k] == pl$n_models] = quantile(
                      sim_subsetresults(sim_vals[j], pl, 
                                        cases$cc_adj[k], cases$thres_ignore[k], cases$alphas[k], cases$n_models[k]), 
                      probs = 1 - cases$alphas[k])
    }
  }
  return(res_list)
}


#' Create a named array matching a list
#' 
#' @param pl [List] :: List of simulation parameters, as given by set_sim_param()
#' 
#' @return [Array] :: NA-filled named array
#' 
#' @export
#' 
setup_array = function(pl) {
  ## creates an array that names things properly
  if (!is.list(pl)) { stop("Input is not a list") }
  
  lengths = sapply(pl, length)[1:4]
  namelist = list()
  for (j in 1:4) {
    namelist[[names(pl)[j]]] = pl[[j]]
  }
  
  res = array(NA, dim = lengths, dimnames = namelist)
  return(res)
}


#' Extracts results matching a subset of parameters
#' 
#' @param rl [List] :: Should be output of sim_hyptest (or something similar) 
#' @param pl [List] :: List of simulation parameters, as given by set_sim_param()
#' @param cc_adj [int] :: Amount of SE's away from the correlation estimate used (how conservative? 0 means no adjustment (and requires large sample for guarantees; larger values give a conservative p-value))
#' @param thres_ignore [int] :: Ignore edge groups with fewer than this many edges
#' @param alphas [int] :: Size of test
#' @param n_models [int] :: Number of edge partitions to use for testing
#' 
#' @return [Matirx] :: A matrix of results of a certain type
#' 
#' @export
#' 
sim_subsetresults = function(rl, pl, cc_adj, thres_ignore, alphas, n_models) { 
  ## is similar to extract_result_list (but not sure to remove extract_result_list yet)
  ## extracts results of a certain type
  
  i1 = which(pl$cc_adj == cc_adj)
  i2 = which(pl$thres_ignore == thres_ignore)
  i3 = which(pl$alphas == alphas)
  i4 = which(pl$n_models == n_models)
  
  res = matrix(-1, nrow = length(rl[[1]]), ncol = length(rl))
  for(j in seq_along(rl)) {
    res[,j] = sapply(rl[[j]], function(x) { x[i1, i2, i3, i4]} )
  }
  return(res)
}


## TODO: [Documentation-AUTO] Check/fix Roxygen2 Documentation (sim_power_rpart)
#' Simulates the power for different pairs of generating models
#' 
#' @param GL [list] :: List of generating models (NetModPairs)
#' @param NL [list] :: List of null-hypothesis models (NetModPairs)
#' @param FL [list] :: List of fitting model parameters
#' @param attrib [dataframe] :: Parameters of simulations
#' @param descrip [char] :: Description of simulation
#' @param outfile [char] :: Filename to store simulation results
#' @param Nsim [int, 500] :: Number of simulations
#' @param Nsim_crit [int, 500] :: Number of simulations for critical values
#' @param Nobs [int, 1] :: Number of network observations
#' @param verbose [int, 0] :: Verbosity level (from 0 to 3), larger means more output 
#' @param pl [List] :: List of simulation parameters, typically generated by a call to set_sim_param()
#' 
#' @return [List] :: List of power-simulation results
#' 
#' @export
#' 
sim_power_rpart = function(GL, NL, FL, attrib, descrip, outfile, Nsim = 500, Nsim_crit = 500, Nobs = 1, verbose = 0, pl = set_sim_param()) {
  ## then, will also need a function that helps generate the lists of models? maybe? 
  ## for simulations -- given a list of generating models, a list of null-hypothesis models (to generate crit values from), and a corresspnding list of fitting models: 
  
  ## for each pair, simulate the critical values
  ## then -- do simulation
  
  ## input list of generating models is GL, null-hyp -> NL, fitting models -> FL
  if (FALSE) {
    GL = list(NetworkModelPair(m1 = NetworkModelSBM(set_model_param(Nnodes = 30)), is_null = TRUE), 
              NetworkModelPair(m1 = NetworkModelSBM(set_model_param(Nnodes = 30)), is_null = TRUE))
    NL = GL
    FL = list(set_model_param(Nnodes = 30), set_model_param(Nnodes = 30))
    Nsim = 200
    Nsim_crit = 200
    Nobs = 1
    verbose = 5
    pl = set_sim_param()
  }
  
  if (length(GL) != length(NL) || length(NL) != length(FL)) { stop("The model lists are not compatible") }  
  power_list = list()
  cases = expand.grid(pl)
  
  ## Do simulations: 
  for (S in seq_along(GL)) {
    
    ## If FL contains networkstructlists, then use those for everything. otherwise, generate a new one each time...
    if (is(FL[[S]], "NetworkStructList")) { 
      if (verbose > 0) { cat("===== Simulation Number: ", S, " --- (Simulating Critical Values) =====\n", sep = "") }
      critvals = sim_critvals(NetMPair = NL[[S]], Nsim = Nsim_crit, Nobs = Nobs, fit_NetSList = FL[[S]], pl = pl, verbose = verbose)
      
      if (verbose > 0) { cat("===== Simulation Number: ", S, " --- (Simulating Power) =====\n", sep = "") }
      sim_res = sim_hyptest(gen_NetMPair = GL[[S]], fit_NetSList = FL[[S]], Nobs = Nobs, Nsim = Nsim, pl = pl, verbose = verbose)
      
      
    } else {
      if (verbose > 0) { cat("===== Simulation Number: ", S, " --- (Simulating Critical Values) =====\n", sep = "") }
      critvals = sim_critvals(NetMPair = NL[[S]], Nsim = Nsim_crit, Nobs = Nobs, fit_models_params = FL[[S]], pl = pl, verbose = verbose)
      
      if (verbose > 0) { cat("===== Simulation Number: ", S, " --- (Simulating Power) =====\n", sep = "") }
      sim_res = sim_hyptest(gen_NetMPair = GL[[S]], fitm_params = FL[[S]], Nobs = Nobs, Nsim = Nsim, pl = pl, verbose = verbose)
    }
    
    ## Use critical values to reject if necessary
    if (verbose > 0) { cat("===== Simulation Number: ", S, " --- (Computing Power) =====\n", sep = "") }
    power_list[[S]] = list()
    
    
    for(j in seq_along(pl$pval_adj$fx)) {
      power_list[[S]][[j]] = setup_array(pl)
      for(k in seq_len(nrow(cases))) {
        i1 = which(cases$cc_adj[k] == pl$cc_adj); i2 = cases$thres_ignore[k] == pl$thres_ignore
        i3 = cases$alphas[k] == pl$alphas; i4 = cases$n_models[k] == pl$n_models
        
        test_stats = sim_subsetresults(sim_res, pl, cases$cc_adj[k], cases$thres_ignore[k], cases$alphas[k], cases$n_models[k])
        
        if (names(pl$pval_adj$fx)[j] == "mult_bonferroni") {
          power_list[[S]][[j]][i1, i2, i3, i4] = mean(test_stats[,j] < 0.05 / cases$n_models[k])
        } else {
          power_list[[S]][[j]][i1, i2, i3, i4] = mean(test_stats[,j] > critvals[[j]][i1, i2, i3, i4])
        }
      }
    }    
    
    ## Save to file
    reslist = list(GL = GL, NL = NL, FL = FL, pl = pl, attrib = attrib, descrip = descrip, power = power_list)
    save(reslist, file = outfile)
  }
  
  
  return(reslist)
}




## TODO: [Update] this function to work with the new simulation functions
#' Extracts p-values (or aggregated p-values) for a specific class of testing. 
#' 
#' @param full_output Full result list from sim_test
#' @param cc_adj Value for correlation adjustment
#' @param thres_ignore Value for thresholding
#' @param alphas Size of test
#' @param n_models Number of fixed models to use
#' @param raw_pvals T/F: Output raw p-values as a list?
#' 
#' @return Vector of aggregated p-values (and a list of raw p-values if desired)
#' 
#' @export
#' 
extract_result_list = function(full_output, cc_adj = 2, thres_ignore = 5, alphas = 0.05, n_models = 50, raw_pvals = FALSE) {
  
  rl = full_output$result_list
  pl = full_output$pl
  pvl = full_output$pval_reslist
  
  i1 = which(pl$cc_adj == cc_adj)
  i2 = which(pl$thres_ignore == thres_ignore)
  i3 = which(pl$n_models == n_models)
  i4 = which(pl$alphas == alphas)
  
  #   result_list[[f]][[j]] = array(0, dim = c(length(pl$cc_adj), length(pl$thres_ignore), length(pl$n_models), length(pl$alphas)))  
  res = matrix(0, nrow = length(rl[[1]]), ncol = length(rl))
  for(j in 1:length(rl)) {
    inl = rl[[j]]    
    for(k in seq_along(inl)) {
      res[k,j] = inl[[k]][i1,i2,i3,i4]
    }
  }
  
  if (raw_pvals) {
    pvals = list()
    for(k in seq_along(inl)) {
      pvals[[k]] = pvl[[k]][i1, i2, 1:n_models]
    }
    return(list(res = res, rawpvallist = pvals))
  } else {
    return(res)
  }
}


